### ISSUE TITLE
1.20.1  Causes a crash when destroying blocks on Valkyrien Skies ships

### ISSUE THREAD

**Issue by LMaxRouterCN** [Majrusz/MinecraftMods#112]
mod version 1.10.8
Valkyrien Skies version 2.3.0 beta5
crash report here:
[错误报告-2024-12-25_17.13.30.zip](https://github.com/user-attachments/files/18245361/-2024-12-25_17.13.30.zip)

**Comment by LMaxRouterCN** [comment]
Here is chatgpt says:

Bug Description:

The game crashes with an ArrayIndexOutOfBoundsException when rendering particles related to the TelekinesisParticle class in the Majrusz Enchantments mod. The error occurs because an invalid index (-1) is used when accessing a sprite in the particle texture set.

Crash Log:

net.minecraft.ReportedException: Ticking Particle
    at net.minecraft.client.particle.ParticleEngine.m_107393_(ParticleEngine.java:399)
    at net.minecraft.client.particle.ParticleEngine.m_107384_(ParticleEngine.java:375)
    ...
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 4
    at com.google.common.collect.RegularImmutableList.get(RegularImmutableList.java:77)
    at net.minecraft.client.particle.ParticleEngine$MutableSpriteSet.m_5819_(ParticleEngine.java:553)
    at com.majruszsenchantments.particles.TelekinesisParticle.m_5989_(TelekinesisParticle.java:39)
    at net.minecraft.client.particle.ParticleEngine.m_107393_(ParticleEngine.java:393)
    ...
Steps to Reproduce:

Install Majrusz Enchantments mod.
Trigger the Telekinesis effect or render the associated particles.
Suggested Fix:
Check the handling of the sprite index in the TelekinesisParticle class to ensure the index is valid before accessing the sprite list. Ensure proper bounds checking when retrieving a sprite from the particle set to avoid an ArrayIndexOutOfBoundsException.

**Comment by Polaria1** [comment]
I'm also experiencing this issue. MC Version 1.20.1, Fabric 1.6.10, Valkyrien Skies 2.3.0-beta5

Crash log: https://pastebin.com/Nty0xsyk

**Comment by allanonmage** [comment]
I ran into this issue from a different angle. I was playtesting my modpack and got a client crash (server stayed running) when trying to mine deepslate wanderlite ore (naturally generated, player placed, and also in whatever state it is when two combine and they start glowing). Removing the telekenesis enchantment allowed me to mine it properly without a crash.

Fabric 1.20.1 

Server
https://moddermore.net/list/tRJW81cDgFPD

Client
https://moddermore.net/list/qZpNyAcupOl-
