### ISSUE TITLE
crashes on first launch but fine after

### ISSUE THREAD

**Issue by Tokerot** [Majrusz/MinecraftMods#48]
almost every time i go to start my mod-pack (with about 200 mods so hard to individually test) on the first launch it crashes with an error loading wonderful enchantments
but if i relaunch it starts up fine and works fine in game

> -- Head --
Thread: Render thread
Stacktrace:
	at java.util.HashMap.computeIfAbsent(HashMap.java:1221) ~[?:?] {re:mixin}
-- MOD wonderful_enchantments --
Details:
	Mod File: wonderful-enchantments-1.18.1-1.6.1.jar
	Failure message: Wonderful Enchantments (wonderful_enchantments) encountered an error during the sided_setup event phase
		java.util.ConcurrentModificationException: null
	Mod Version: 1.6.1
	Mod Issue URL: https://github.com/Majrusz/WonderfulEnchantmentsMod/issues
	Exception message: java.util.ConcurrentModificationException
Stacktrace:
	at java.util.HashMap.computeIfAbsent(HashMap.java:1221) ~[?:?] {re:mixin}
	at net.minecraft.client.renderer.item.ItemProperties.register(ItemProperties.java:60) ~[client-1.18.1-20211210.034407-srg.jar%23249!:?] {re:classloading,pl:runtimedistcleaner:A}
	at com.wonderfulenchantments.RegistryHandlerClient.setup(RegistryHandlerClient.java:26) ~[wonderful-enchantments-1.18.1-1.6.1.jar%23245!:1.6.1] {re:classloading,pl:runtimedistcleaner:A}
	at com.wonderfulenchantments.RegistryHandler.doClientSetup(RegistryHandler.java:117) ~[wonderful-enchantments-1.18.1-1.6.1.jar%23245!:1.6.1] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[javafmllanguage-1.18.1-39.0.9.jar%23251!:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121) ~[fmlcore-1.18.1-39.0.9.jar%23250!:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

**Comment by Majrusz** [comment]
Should not be an issue anymore in the latest release
