### ISSUE TITLE
Invalid update JSON url (404)

### ISSUE THREAD

**Issue by ChiefArug** [Majrusz/MinecraftMods#60]
```
[Forge Version Check/INFO] [net.minecraftforge.fml.VersionChecker/]: [majruszsenchantments] Starting version check at https://raw.githubusercontent.com/Majrusz/MajruszsEnchantmentsMod/1.19.X/update.json
Forge Version Check/DEBUG] [net.minecraftforge.fml.VersionChecker/]: [majruszsenchantments] Received version check data:
404: Not Found
[Forge Version Check/WARN] [net.minecraftforge.fml.VersionChecker/]: Failed to process update information
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was NUMBER at line 1 column 4 path $
	at com.google.gson.Gson.fromJson(Gson.java:975) ~[gson-2.8.9.jar%23121!/:?]
	at com.google.gson.Gson.fromJson(Gson.java:928) ~[gson-2.8.9.jar%23121!/:?]
	at com.google.gson.Gson.fromJson(Gson.java:877) ~[gson-2.8.9.jar%23121!/:?]
	at com.google.gson.Gson.fromJson(Gson.java:848) ~[gson-2.8.9.jar%23121!/:?]
	at net.minecraftforge.fml.VersionChecker$1.process(VersionChecker.java:183) ~[fmlcore-1.19.2-43.2.1.jar%23818!/:?]
	at java.lang.Iterable.forEach(Iterable.java:75) [?:?]
	at net.minecraftforge.fml.VersionChecker$1.run(VersionChecker.java:114) [fmlcore-1.19.2-43.2.1.jar%23818!/:?]
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was NUMBER at line 1 column 4 path $
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:384) ~[gson-2.8.9.jar%23121!/:?]
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:183) ~[gson-2.8.9.jar%23121!/:?]
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145) ~[gson-2.8.9.jar%23121!/:?]
	at com.google.gson.Gson.fromJson(Gson.java:963) ~[gson-2.8.9.jar%23121!/:?]
	... 6 more
```
Nothing crash worthy, just an unneeded stack trace in the logs.

**Comment by Majrusz** [comment]
Hi, my bad, I forgot to keep backward compatibility. Update the mod to the latest version and it should not log such warnings. Anyway, thanks for the report!
