### ISSUE TITLE
java.lang.IllegalArgumentException: Bound must be positive

### ISSUE THREAD

**Issue by Quezler** [Majrusz/MinecraftMods#64]
The fishing rod occasionally refuses to come back up in the [Cottage Witch 1.19-1.7.zip](https://www.curseforge.com/minecraft/modpacks/cottage-witch/files/4406568) modpack:
```
java.lang.IllegalArgumentException: Bound must be positive
        at net.minecraft.world.level.levelgen.BitRandomSource.m_188503_(BitRandomSource.java:22) ~[server-1.19.2-20220805.130853-srg.jar%23589!/:?] {re:classloading}
        at com.mlib.Random.nextInt(Random.java:51) ~[majrusz-library-1.19.2-3.1.0.jar%23488!/:3.1.0] {re:classloading}
        at com.mlib.Random.nextInt(Random.java:55) ~[majrusz-library-1.19.2-3.1.0.jar%23488!/:3.1.0] {re:classloading}
        at com.majruszsenchantments.enchantments.FishingFanaticEnchantment$Modifier.increaseLoot(FishingFanaticEnchantment.java:129) ~[majruszs-enchantments-1.19.2-1.8.0.jar%23490!/:1.8.0] {re:classloading}
        at com.mlib.gamemodifiers.Contexts.lambda$accept$0(Contexts.java:31) ~[majrusz-library-1.19.2-3.1.0.jar%23488!/:3.1.0] {re:classloading}
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?] {re:mixin}
        at java.util.Collections$SynchronizedCollection.forEach(Collections.java:2131) ~[?:?] {}
        at com.mlib.gamemodifiers.Contexts.accept(Contexts.java:29) ~[majrusz-library-1.19.2-3.1.0.jar%23488!/:3.1.0] {re:classloading}
        at com.mlib.gamemodifiers.contexts.OnExtraFishingLootCheck$Context.accept(OnExtraFishingLootCheck.java:26) ~[majrusz-library-1.19.2-3.1.0.jar%23488!/:3.1.0] {re:classloading}
        at com.mlib.features.FishingLootIncreaser.dispatchContext(FishingLootIncreaser.java:44) ~[majrusz-library-1.19.2-3.1.0.jar%23488!/:3.1.0] {re:classloading}
        at com.mlib.features.FishingLootIncreaser.increaseLoot(FishingLootIncreaser.java:33) ~[majrusz-library-1.19.2-3.1.0.jar%23488!/:3.1.0] {re:classloading}
        at com.mlib.gamemodifiers.Contexts.lambda$accept$0(Contexts.java:31) ~[majrusz-library-1.19.2-3.1.0.jar%23488!/:3.1.0] {re:classloading}
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?] {re:mixin}
        at java.util.Collections$SynchronizedCollection.forEach(Collections.java:2131) ~[?:?] {}
        at com.mlib.gamemodifiers.Contexts.accept(Contexts.java:29) ~[majrusz-library-1.19.2-3.1.0.jar%23488!/:3.1.0] {re:classloading}
        at com.mlib.gamemodifiers.contexts.OnItemFished$Context.onDimensionChanged(OnItemFished.java:29) ~[majrusz-library-1.19.2-3.1.0.jar%23488!/:3.1.0] {re:classloading}
        at com.mlib.gamemodifiers.contexts.__Context_onDimensionChanged_ItemFishedEvent.invoke(.dynamic) ~[majrusz-library-1.19.2-3.1.0.jar%23488!/:3.1.0] {re:classloading,pl:eventbus:B}
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.3.jar%2351!/:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2351!/:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2351!/:?] {}
        at net.minecraft.world.entity.projectile.FishingHook.m_37156_(FishingHook.java:417) ~[server-1.19.2-20220805.130853-srg.jar%23589!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:domesticationinnovation.mixins.json:FishingHookMixin,pl:mixin:A}
        at net.minecraft.world.item.FishingRodItem.m_7203_(FishingRodItem.java:23) ~[server-1.19.2-20220805.130853-srg.jar%23589!/:?] {re:classloading}
        at net.minecraft.world.item.ItemStack.m_41682_(ItemStack.java:266) ~[server-1.19.2-20220805.130853-srg.jar%23589!/:?] {re:mixin,xf:fml:forge:itemstack,re:classloading,xf:fml:forge:itemstack,pl:mixin:APP:mixins.mlib.json:MixinItemStack,pl:mixin:APP:mixins.hibernalherbs.json:ItemStackMixin,pl:mixin:APP:canary.mixins.json:block.hopper.ItemStackMixin,pl:mixin:APP:canary.mixins.json:item.ItemStackMixin,pl:mixin:APP:placebo.mixins.json:ItemStackMixin,pl:mixin:APP:creatures-and-beasts.mixins.json:MixinItemStack,pl:mixin:APP:itemfilters-common.mixins.json:ItemStackMixin,pl:mixin:APP:tarotcards.mixins.json:ItemStackMixin,pl:mixin:APP:quark.mixins.json:ItemStackMixin,pl:mixin:A}
        at net.minecraft.server.level.ServerPlayerGameMode.m_6261_(ServerPlayerGameMode.java:286) ~[server-1.19.2-20220805.130853-srg.jar%23589!/:?] {re:mixin,re:computing_frames,re:classloading,pl:mixin:APP:questsadditions.mixins.json:MixinPlayerInteractionManager,pl:mixin:A}
        at net.minecraft.server.network.ServerGamePacketListenerImpl.m_5760_(ServerGamePacketListenerImpl.java:1089) ~[server-1.19.2-20220805.130853-srg.jar%23589!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:forgivingvoid.mixins.json:ServerGamePacketListenerImplAccessor,pl:mixin:APP:davespotioneering.mixins.json:ServerPlayNetHandlerMixin,pl:mixin:APP:nochatreports.mixins.json:server.MixinServerGamePacketListenerImpl,pl:mixin:APP:connectivity.mixins.json:ServerPlayNetHandlerMixin,pl:mixin:A}
        at net.minecraft.network.protocol.game.ServerboundUseItemPacket.m_5797_(ServerboundUseItemPacket.java:29) ~[server-1.19.2-20220805.130853-srg.jar%23589!/:?] {re:classloading}
        at net.minecraft.network.protocol.game.ServerboundUseItemPacket.m_5797_(ServerboundUseItemPacket.java:7) ~[server-1.19.2-20220805.130853-srg.jar%23589!/:?] {re:classloading}
        at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:22) ~[server-1.19.2-20220805.130853-srg.jar%23589!/:?] {re:classloading}
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.19.2-20220805.130853-srg.jar%23589!/:?] {re:classloading,re:mixin}
        at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[server-1.19.2-20220805.130853-srg.jar%23589!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.19.2-20220805.130853-srg.jar%23589!/:?] {re:computing_frames,re:mixin,re:classloading}
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:763) ~[server-1.19.2-20220805.130853-srg.jar%23589!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:157) ~[server-1.19.2-20220805.130853-srg.jar%23589!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[server-1.19.2-20220805.130853-srg.jar%23589!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:746) ~[server-1.19.2-20220805.130853-srg.jar%23589!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:740) ~[server-1.19.2-20220805.130853-srg.jar%23589!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:140) ~[server-1.19.2-20220805.130853-srg.jar%23589!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:726) ~[server-1.19.2-20220805.130853-srg.jar%23589!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:658) ~[server-1.19.2-20220805.130853-srg.jar%23589!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[server-1.19.2-20220805.130853-srg.jar%23589!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at java.lang.Thread.run(Thread.java:833) [?:?] {re:mixin}
```

**Comment by Majrusz** [comment]
Hi, thanks for the report it has been fixed in 3.2.0 library version
